[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["cargo"] }
env_logger = "0.11.5"
log = "0.4.22"
rustix = { version = "0.38.39", features = ["fs", "mm", "shm", "use-libc"] }
